baseURL = "https://clay.visioninit.dev/"
languageCode = "en-us"
title = "Georgette Clay MA, Ed.S | Public Speaking & Curriculum Design"

[pagination]
pagerSize = 12

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# Main Menu
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Expertise"
url = "#expertise"
weight = 3
[[menu.main]]
name = "Highlights"
url = "#awards"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 6

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "Copyright © Georgette Clay 2024"
# We're using fabform.io for form handling, paste your fabform url below
form_action_url = "YOUR_FABFORM_URL_HERE"
# Add the new scheduling link parameter here
scheduling_link = "https://cal.com/visioninit/temp./"
googleAnalytics = "YOUR_GOOGLE_ANALYTICS_CODE"
logo_text = "Georgette Clay"
description = "Georgette Clay, an experienced educator and public speaking coach, specializes in curriculum design, program evaluation, and empowering professionals to communicate with clarity and confidence."

[params.address]
address = "New York, NY 10016"
email = "georgette_clay@yahoo.com"
phone = "347-977-1532"
